default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: election_development

test:
  <<: *default
  database: election_test

production:
#  <<: *default
#  database: election_development
#heroku:
  adapter: postgresql
  encoding: unicode
  database: ENV['DATABASE_URL']
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORDs']